/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;

import java.awt.Component;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;

/**
 *
 * @author jsaca
 */
public class EditarEquipos extends javax.swing.JInternalFrame {

    Metodos metodos = new Metodos();
    int cod_equipo;
    
    public EditarEquipos(int cod_equipo_seleccionado) {
        initComponents();
        Rectangle screenSize = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration().getBounds();
        int width = (int)screenSize.getWidth();
        int height = (int)screenSize.getHeight();
        
        this.setSize(width, height);
        jlEditarEquipo.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnTerminar.setAlignmentX(Component.CENTER_ALIGNMENT);
        NuevoEquipo ne = new NuevoEquipo();
        cod_equipo = cod_equipo_seleccionado;
        ne.mostrarJugadores(ne.cod_sin_equipo, jtJugadoresFuera);
        ne.mostrarJugadores(cod_equipo_seleccionado, jtJugadoresEnEquipo);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAgregarEquipo = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        jlEditarEquipo = new javax.swing.JLabel();
        jlJugadores = new javax.swing.JLabel();
        btnEliminarEquipo = new javax.swing.JButton();
        jlJugadores1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtJugadoresFuera = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtJugadoresEnEquipo = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        btnAgregarEquipo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnAgregarEquipo.setText("Agregar Jugador");
        btnAgregarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEquipoActionPerformed(evt);
            }
        });

        btnTerminar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnTerminar.setText("Terminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        jlEditarEquipo.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jlEditarEquipo.setForeground(new java.awt.Color(255, 0, 0));
        jlEditarEquipo.setText("Editar Equipo");

        jlJugadores.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlJugadores.setForeground(new java.awt.Color(255, 0, 0));
        jlJugadores.setText("Jugadores en el Equipo");

        btnEliminarEquipo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnEliminarEquipo.setText("Eliminar Jugador");
        btnEliminarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEquipoActionPerformed(evt);
            }
        });

        jlJugadores1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlJugadores1.setForeground(new java.awt.Color(255, 0, 0));
        jlJugadores1.setText("Jugadores Fuera del Equipo");

        jtJugadoresFuera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtJugadoresFuera);

        jtJugadoresEnEquipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jtJugadoresEnEquipo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jlJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(694, 694, 694)
                                .addComponent(jlJugadores1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(647, 647, 647)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnTerminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jlEditarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(405, 405, 405))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(btnEliminarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(761, 761, 761)
                                .addComponent(btnAgregarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(24, 24, 24)))
                        .addGap(285, 285, 285))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addGap(346, 346, 346)
                        .addComponent(jScrollPane3)
                        .addGap(75, 75, 75))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jlEditarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(137, 137, 137)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlJugadores1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(338, 338, 338))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(296, 296, 296)
                        .addComponent(btnTerminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEquipoActionPerformed
        metodos.cambiarEquipoDeJugador(cod_equipo, jtJugadoresFuera);
        metodos.mostrarJugadores(metodos.sin_equipo, jtJugadoresFuera);
        metodos.mostrarJugadores(cod_equipo, jtJugadoresEnEquipo);
    }//GEN-LAST:event_btnAgregarEquipoActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        Menu menu = new Menu();
        
        Main.Escritorio.add(menu);
        menu.setVisible(true);
        menu.setSize(Main.Escritorio.getSize());
        
        this.dispose();
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnEliminarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEquipoActionPerformed
        metodos.cambiarEquipoDeJugador(metodos.sin_equipo, jtJugadoresEnEquipo);
        metodos.mostrarJugadores(metodos.sin_equipo, jtJugadoresFuera);
        metodos.mostrarJugadores(cod_equipo, jtJugadoresEnEquipo);
    }//GEN-LAST:event_btnEliminarEquipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEquipo;
    private javax.swing.JButton btnEliminarEquipo;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jlEditarEquipo;
    private javax.swing.JLabel jlJugadores;
    private javax.swing.JLabel jlJugadores1;
    private javax.swing.JTable jtJugadoresEnEquipo;
    private javax.swing.JTable jtJugadoresFuera;
    // End of variables declaration//GEN-END:variables

}
