
package CRUD;

import java.awt.Component;

/**
 *
 * @author jsaca
 */
public class Menu extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        jlMenu.setAlignmentX(Component.CENTER_ALIGNMENT);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNuevoPartido = new javax.swing.JButton();
        btnNuevoJugador = new javax.swing.JButton();
        btnEquipos = new javax.swing.JButton();
        btnVerEstadisticas = new javax.swing.JButton();
        jlMenu = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        btnNuevoPartido.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnNuevoPartido.setText("Nuevo Partido");
        btnNuevoPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPartidoActionPerformed(evt);
            }
        });

        btnNuevoJugador.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnNuevoJugador.setText("Nuevo Jugador");
        btnNuevoJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoJugadorActionPerformed(evt);
            }
        });

        btnEquipos.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnEquipos.setText("Equipos");
        btnEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquiposActionPerformed(evt);
            }
        });

        btnVerEstadisticas.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnVerEstadisticas.setText("Ver Estadisticas");
        btnVerEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEstadisticasActionPerformed(evt);
            }
        });

        jlMenu.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jlMenu.setForeground(new java.awt.Color(255, 0, 0));
        jlMenu.setText("Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevoPartido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(384, 384, 384)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevoJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(587, 587, 587)
                .addComponent(jlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(588, 588, 588))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoPartido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(148, 148, 148)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEquipos)
                    .addComponent(btnVerEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(308, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEstadisticasActionPerformed
        Estadisticas estadisticas = new Estadisticas();
        
        Main.Escritorio.add(estadisticas);
        estadisticas.setVisible(true);
        estadisticas.setSize(Main.Escritorio.getSize());
        
        this.dispose();
    }//GEN-LAST:event_btnVerEstadisticasActionPerformed

    private void btnNuevoPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPartidoActionPerformed
        PrePartido nuevoPartido = new PrePartido();
        
        Main.Escritorio.add(nuevoPartido);
        nuevoPartido.setVisible(true);
        nuevoPartido.setSize(Main.Escritorio.getSize());
        this.dispose();
        
    }//GEN-LAST:event_btnNuevoPartidoActionPerformed

    private void btnNuevoJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoJugadorActionPerformed
        NuevoJugador nuevoJugador = new NuevoJugador();
        
        Main.Escritorio.add(nuevoJugador);
        nuevoJugador.setVisible(true);
        nuevoJugador.setSize(Main.Escritorio.getSize());
        
        this.dispose();
    }//GEN-LAST:event_btnNuevoJugadorActionPerformed

    private void btnEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquiposActionPerformed
        Equipos equipos = new Equipos();
        
        Main.Escritorio.add(equipos);
        equipos.setVisible(true);
        equipos.setSize(Main.Escritorio.getSize());
        
        this.dispose();
    }//GEN-LAST:event_btnEquiposActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEquipos;
    private javax.swing.JButton btnNuevoJugador;
    private javax.swing.JButton btnNuevoPartido;
    private javax.swing.JButton btnVerEstadisticas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlMenu;
    // End of variables declaration//GEN-END:variables
}
