// para el inner join
//https://www.youtube.com/watch?v=V3TwO7wP8u4

package CRUD;

import com.sun.glass.events.KeyEvent;
import conexion.conexionSQL;
import java.awt.Component;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;


public class NuevoPartido extends javax.swing.JInternalFrame {
    
    conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();
    
    Metodos metodos =new Metodos();
    String equipoA;
    String equipoB;
    int set = 1;
    int puntosA = 0;
    int puntosB = 0;
    int setsA = 0;
    int setsB = 0;
    boolean saca;
    int [] cod_titulares = new int [6];
    int [] cod_cambios = new int [6];
    int cod_partido = metodos.codPartido();
    int cod_movimiento = 0;
    int cod_area = 0;
    int cod_punto;
    int jugador;
    int cod_equipo;
    
    String[] titulos = {"Codigo", "Nombre", "Apellido", "Numero", "Posicion", "Codigo Equipo"};
    DefaultTableModel modeloTitulares = new DefaultTableModel(null, titulos);
    DefaultTableModel modeloCambios = new DefaultTableModel(null, titulos);
    
    DefaultTableModel modeloTitulares2 = new DefaultTableModel(null, titulos);
    DefaultTableModel modeloCambios2 = new DefaultTableModel(null, titulos);
     
   
    boolean bandera = false;
    
    DefaultTableModel modeloJugadores = new DefaultTableModel(null, titulos);
    
    String equipo_a;
    String equipo_b;
    
    
    int titulares = 0;
    int cambios = 0;
    

    public NuevoPartido(DefaultTableModel modeloTitulares, DefaultTableModel modeloCambios, boolean bandera, int [] cod_titulares, int [] cod_cambios, String equipoA, String equipoB) {
        initComponents();
        
        Rectangle screenSize = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration().getBounds();
        int width = (int)screenSize.getWidth();
        int height = (int)screenSize.getHeight();
        
        this.setSize(width, height);
        
        System.arraycopy(cod_titulares, 0, this.cod_titulares, 0, 6);
        System.arraycopy(cod_cambios, 0, this.cod_cambios, 0, 6);

        this.equipoA = equipoA;
        this.equipoB = equipoB;
        
        this.setMaximumSize(Main.Escritorio.getMaximumSize());
        
        jlEquipoA.setText(equipoA);
        jlEquipoB.setText(equipoB);
        jlSet.setText("Set: " + Integer.toString(set));
        jlPuntosA.setText("Puntos: " + Integer.toString(puntosA));
        jlPuntosB.setText("Puntos: " + Integer.toString(puntosB));
        jlSetsGanadosA.setText("Sets Ganados: " + Integer.toString(setsA));
        jlSetsGanadosB.setText("Sets Ganados: " + Integer.toString(setsB));
        
        saca = bandera;
        
        this.bandera = saca;
       
        
        
        Saque();
        CrearSet();
        jl1.setText(Integer.toString(cod_titulares[0]));
        jl2.setText(Integer.toString(cod_titulares[5]));
        jl3.setText(Integer.toString(cod_titulares[4]));
        jl4.setText(Integer.toString(cod_titulares[3]));
        jl5.setText(Integer.toString(cod_titulares[2]));
        jl6.setText(Integer.toString(cod_titulares[1]));
        
        MostrarJugadores(cod_titulares, jtTitulares);
        MostrarJugadores(cod_cambios, jtCambios);
        
        cod_equipo = Integer.parseInt(jtTitulares.getValueAt(0, 5).toString());
        
        // <editor-fold defaultstate="collapsed" desc="Key Shortcuts">
        btnSaque.setMnemonic(KeyEvent.VK_S);
        btnRemate.setMnemonic(KeyEvent.VK_R);
        btnBloqueo.setMnemonic(KeyEvent.VK_B);
        btnRecibo.setMnemonic(KeyEvent.VK_E);
        btnColoque.setMnemonic(KeyEvent.VK_C);
        btnDefensa.setMnemonic(KeyEvent.VK_D);
        btnA1.setMnemonic(KeyEvent.VK_1);
        btnA2.setMnemonic(KeyEvent.VK_2);
        btnA3.setMnemonic(KeyEvent.VK_3);
        btnA4.setMnemonic(KeyEvent.VK_4);
        btnA5.setMnemonic(KeyEvent.VK_5);
        btnA6.setMnemonic(KeyEvent.VK_6);
        btnPuntoEnContra.setMnemonic(KeyEvent.VK_M);
        btnPunto.setMnemonic(KeyEvent.VK_P);
        btnContinuante.setMnemonic(KeyEvent.VK_N);
        // </editor-fold>  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NuevoSet = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtTitulares2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtCambios2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtJugadores = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegresar_Titulares = new javax.swing.JToggleButton();
        btn_Regresar_Cambio = new javax.swing.JToggleButton();
        btnTitular = new javax.swing.JButton();
        btnCambio1 = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        pnlRotuloPartido = new javax.swing.JPanel();
        jlEquipoA = new javax.swing.JLabel();
        jlEquipoB = new javax.swing.JLabel();
        jlSet = new javax.swing.JLabel();
        jlPuntosA = new javax.swing.JLabel();
        jlPuntosB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlSetsGanadosB = new javax.swing.JLabel();
        jlSetsGanadosA = new javax.swing.JLabel();
        pnlTablaPartido = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTitulares = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCambios = new javax.swing.JTable();
        btnCambio = new javax.swing.JButton();
        pnlJugadas = new javax.swing.JPanel();
        btnSaque = new javax.swing.JToggleButton();
        btnRemate = new javax.swing.JToggleButton();
        btnBloqueo = new javax.swing.JToggleButton();
        btnRecibo = new javax.swing.JToggleButton();
        btnColoque = new javax.swing.JToggleButton();
        btnDefensa = new javax.swing.JToggleButton();
        pnlAreas = new javax.swing.JPanel();
        btnA1 = new javax.swing.JToggleButton();
        btnA2 = new javax.swing.JToggleButton();
        btnA3 = new javax.swing.JToggleButton();
        btnA6 = new javax.swing.JToggleButton();
        btnA5 = new javax.swing.JToggleButton();
        btnA4 = new javax.swing.JToggleButton();
        btnPuntoEnContra = new javax.swing.JButton();
        btnContinuante = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jl4 = new javax.swing.JLabel();
        jl3 = new javax.swing.JLabel();
        jl2 = new javax.swing.JLabel();
        jl5 = new javax.swing.JLabel();
        jl6 = new javax.swing.JLabel();
        jl1 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(0, 0, 153));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Seleccione la nueva alineacion para el siguiente set");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Seleccione los titulares en el orden que van a hacer las rotaciones");

        jtTitulares2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtTitulares2);

        jtCambios2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jtCambios2);

        jtJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jtJugadores);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Jugadores en el partido");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Cambios");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Titulares");

        btnRegresar_Titulares.setText("Regresar Jugador");

        btn_Regresar_Cambio.setText("Regresar Jugador");

        btnTitular.setText("Titular");
        btnTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitularActionPerformed(evt);
            }
        });

        btnCambio1.setText("Cambio");
        btnCambio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambio1ActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(btnTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCambio1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Regresar_Cambio)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnRegresar_Titulares))
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(66, 66, 66)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegresar_Titulares)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Regresar_Cambio)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCambio1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );

        javax.swing.GroupLayout NuevoSetLayout = new javax.swing.GroupLayout(NuevoSet.getContentPane());
        NuevoSet.getContentPane().setLayout(NuevoSetLayout);
        NuevoSetLayout.setHorizontalGroup(
            NuevoSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NuevoSetLayout.setVerticalGroup(
            NuevoSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        pnlRotuloPartido.setBackground(new java.awt.Color(102, 102, 102));

        jlEquipoA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlEquipoA.setForeground(new java.awt.Color(255, 255, 255));
        jlEquipoA.setText("Equipo A");

        jlEquipoB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlEquipoB.setForeground(new java.awt.Color(255, 255, 255));
        jlEquipoB.setText("Equipo B");

        jlSet.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlSet.setForeground(new java.awt.Color(255, 255, 255));
        jlSet.setText("Set: ");

        jlPuntosA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlPuntosA.setForeground(new java.awt.Color(255, 255, 255));
        jlPuntosA.setText("Puntos");

        jlPuntosB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlPuntosB.setForeground(new java.awt.Color(255, 255, 255));
        jlPuntosB.setText("Puntos");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Saca: ");

        jlSetsGanadosB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlSetsGanadosB.setForeground(new java.awt.Color(255, 255, 255));
        jlSetsGanadosB.setText("Sets Ganados: ");

        jlSetsGanadosA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jlSetsGanadosA.setForeground(new java.awt.Color(255, 255, 255));
        jlSetsGanadosA.setText("Sets Ganados: ");

        javax.swing.GroupLayout pnlRotuloPartidoLayout = new javax.swing.GroupLayout(pnlRotuloPartido);
        pnlRotuloPartido.setLayout(pnlRotuloPartidoLayout);
        pnlRotuloPartidoLayout.setHorizontalGroup(
            pnlRotuloPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRotuloPartidoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlRotuloPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRotuloPartidoLayout.createSequentialGroup()
                        .addComponent(jlEquipoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(108, 108, 108)
                        .addComponent(jlSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(pnlRotuloPartidoLayout.createSequentialGroup()
                        .addComponent(jlSetsGanadosA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(191, 191, 191))
                    .addGroup(pnlRotuloPartidoLayout.createSequentialGroup()
                        .addComponent(jlPuntosA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(104, 104, 104)
                .addGroup(pnlRotuloPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRotuloPartidoLayout.createSequentialGroup()
                        .addComponent(jlPuntosB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(119, 119, 119))
                    .addGroup(pnlRotuloPartidoLayout.createSequentialGroup()
                        .addComponent(jlSetsGanadosB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(74, 74, 74))
                    .addComponent(jlEquipoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        pnlRotuloPartidoLayout.setVerticalGroup(
            pnlRotuloPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRotuloPartidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRotuloPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRotuloPartidoLayout.createSequentialGroup()
                        .addGroup(pnlRotuloPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEquipoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addComponent(jlSetsGanadosA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlRotuloPartidoLayout.createSequentialGroup()
                        .addComponent(jlEquipoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlSetsGanadosB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRotuloPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPuntosA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlPuntosB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlTablaPartido.setBackground(new java.awt.Color(255, 0, 0));

        jtTitulares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtTitulares);

        jtCambios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtCambios);

        btnCambio.setText("Cambio");
        btnCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTablaPartidoLayout = new javax.swing.GroupLayout(pnlTablaPartido);
        pnlTablaPartido.setLayout(pnlTablaPartidoLayout);
        pnlTablaPartidoLayout.setHorizontalGroup(
            pnlTablaPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaPartidoLayout.createSequentialGroup()
                .addGroup(pnlTablaPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTablaPartidoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(pnlTablaPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)))
                    .addGroup(pnlTablaPartidoLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(171, 171, 171)))
                .addGap(47, 47, 47))
        );
        pnlTablaPartidoLayout.setVerticalGroup(
            pnlTablaPartidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaPartidoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addGap(60, 60, 60)
                .addComponent(btnCambio, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );

        pnlJugadas.setBackground(new java.awt.Color(255, 255, 0));
        pnlJugadas.setForeground(new java.awt.Color(255, 255, 255));

        btnSaque.setMnemonic('X');
        btnSaque.setText("Saque");
        btnSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaqueActionPerformed(evt);
            }
        });
        btnSaque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSaqueKeyPressed(evt);
            }
        });

        btnRemate.setText("Remate");
        btnRemate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemateActionPerformed(evt);
            }
        });

        btnBloqueo.setText("Bloqueo");
        btnBloqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloqueoActionPerformed(evt);
            }
        });

        btnRecibo.setText("Recibo");
        btnRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReciboActionPerformed(evt);
            }
        });

        btnColoque.setText("Pase");
        btnColoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColoqueActionPerformed(evt);
            }
        });

        btnDefensa.setText("Defensa");
        btnDefensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefensaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlJugadasLayout = new javax.swing.GroupLayout(pnlJugadas);
        pnlJugadas.setLayout(pnlJugadasLayout);
        pnlJugadasLayout.setHorizontalGroup(
            pnlJugadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugadasLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlJugadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaque, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(btnRecibo, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addGap(198, 198, 198)
                .addGroup(pnlJugadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJugadasLayout.createSequentialGroup()
                        .addComponent(btnRemate, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addGap(180, 180, 180)
                        .addComponent(btnBloqueo, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJugadasLayout.createSequentialGroup()
                        .addComponent(btnDefensa, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                        .addGap(180, 180, 180)
                        .addComponent(btnColoque, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
        );
        pnlJugadasLayout.setVerticalGroup(
            pnlJugadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugadasLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlJugadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaque, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(btnBloqueo, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(btnRemate, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGroup(pnlJugadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJugadasLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnColoque, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(pnlJugadasLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pnlJugadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRecibo, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(btnDefensa, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
        );

        pnlAreas.setBackground(new java.awt.Color(51, 153, 0));

        btnA1.setText("A1");
        btnA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA1ActionPerformed(evt);
            }
        });

        btnA2.setText("A2");
        btnA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA2ActionPerformed(evt);
            }
        });

        btnA3.setText("A3");
        btnA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA3ActionPerformed(evt);
            }
        });

        btnA6.setText("A6");
        btnA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA6ActionPerformed(evt);
            }
        });

        btnA5.setText("A5");
        btnA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA5ActionPerformed(evt);
            }
        });

        btnA4.setText("A4");
        btnA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAreasLayout = new javax.swing.GroupLayout(pnlAreas);
        pnlAreas.setLayout(pnlAreasLayout);
        pnlAreasLayout.setHorizontalGroup(
            pnlAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAreasLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pnlAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnA1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(btnA4, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addGap(195, 195, 195)
                .addGroup(pnlAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnA2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(btnA5, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addGap(174, 174, 174)
                .addGroup(pnlAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnA6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(btnA3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );
        pnlAreasLayout.setVerticalGroup(
            pnlAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAreasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnA3, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(btnA2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(btnA1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(pnlAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnA6, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(btnA4, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(btnA5, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        btnPuntoEnContra.setText("Punto en Contra");
        btnPuntoEnContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoEnContraActionPerformed(evt);
            }
        });

        btnContinuante.setText("Continuante");
        btnContinuante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuanteActionPerformed(evt);
            }
        });

        btnBack.setText("Regresar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnPunto.setText("Punto");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jl4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jl4.setText("4");

        jl3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jl3.setText("3");

        jl2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jl2.setText("2");

        jl5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jl5.setText("5");

        jl6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jl6.setText("6");

        jl1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jl1.setText("1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl5)
                    .addComponent(jl6)
                    .addComponent(jl1))
                .addGap(59, 59, 59)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl4)
                    .addComponent(jl3)
                    .addComponent(jl2))
                .addGap(67, 67, 67)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jl4)
                .addGap(78, 78, 78)
                .addComponent(jl3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl2)
                .addGap(38, 38, 38))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jl5)
                .addGap(70, 70, 70)
                .addComponent(jl6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl1)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlTablaPartido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(pnlRotuloPartido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlAreas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnlJugadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnPuntoEnContra, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addGap(104, 104, 104)
                        .addComponent(btnContinuante, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addGap(89, 89, 89)
                        .addComponent(btnPunto, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addGap(81, 81, 81))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnlJugadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(40, 40, 40)
                                .addComponent(pnlAreas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnPuntoEnContra, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(btnContinuante, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(btnPunto, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 465, Short.MAX_VALUE)))
                        .addGap(33, 33, 33)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlRotuloPartido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(73, 73, 73)
                        .addComponent(pnlTablaPartido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaqueActionPerformed

    }//GEN-LAST:event_btnSaqueActionPerformed

    private void btnRemateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemateActionPerformed

    private void btnBloqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloqueoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBloqueoActionPerformed

    private void btnReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReciboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReciboActionPerformed

    private void btnColoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnColoqueActionPerformed

    private void btnA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA1ActionPerformed

    private void btnA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA2ActionPerformed

    private void btnA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA3ActionPerformed

    private void btnA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA6ActionPerformed

    private void btnA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA5ActionPerformed

    private void btnA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA4ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Menu menu = new Menu();
        
        Main.Escritorio.add(menu);
        menu.setVisible(true);
        menu.setSize(Main.Escritorio.getSize());
        
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        AreaSeleccionada();
        MovimientoSeleccionado();
        jugador = JugadorSeleccionado();
        if (jugador == 0) {
            JOptionPane.showMessageDialog(null, "Verifique que tiene un jugador seleccionado", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            if (saca == false) {
                saca = true;
                metodos.Rotacion(saca, cod_titulares, jl1, jl2, jl3, jl4, jl5, jl6);
                Saque();
            }

            if (cod_movimiento == 0 || cod_area == 0) {
                JOptionPane.showMessageDialog(null, "Verifique que tenga un area y/o movimiento seleccionado", " ERROR", JOptionPane.ERROR_MESSAGE);
            }else{
                puntosA ++; 
                jlPuntosA.setText("Puntos: " + Integer.toString(puntosA));
                cod_punto = 1;
                NuevoSet();
                Recopilacion();
                ReinicioBotones(); 
            } 
        }
        
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnSaqueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSaqueKeyPressed

    }//GEN-LAST:event_btnSaqueKeyPressed

    private void btnCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambioActionPerformed
        Cambio();
        MostrarJugadores(cod_cambios, jtCambios);
        MostrarJugadores(cod_titulares, jtTitulares);
        jl1.setText(Integer.toString(cod_titulares[0]));
        jl2.setText(Integer.toString(cod_titulares[5]));
        jl3.setText(Integer.toString(cod_titulares[4]));
        jl4.setText(Integer.toString(cod_titulares[3]));
        jl5.setText(Integer.toString(cod_titulares[2]));
        jl6.setText(Integer.toString(cod_titulares[1]));
    }//GEN-LAST:event_btnCambioActionPerformed

    private void btnPuntoEnContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoEnContraActionPerformed
        AreaSeleccionada();
        MovimientoSeleccionado();
        jugador = JugadorSeleccionado();
        if (jugador == 0) {
            JOptionPane.showMessageDialog(null, "Verifique que tiene un jugador seleccionado", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            if (cod_movimiento == 0 || cod_area == 0) {
                JOptionPane.showMessageDialog(null, "Verifique que tenga un area y/o movimiento seleccionado", " ERROR", JOptionPane.ERROR_MESSAGE);
            }else{
                puntosB ++;
                jlPuntosB.setText("Puntos: " + Integer.toString(puntosB));
                saca = false;
                Saque();
                saca = false;
                cod_punto = 2;               
                NuevoSet();
                Recopilacion();
                ReinicioBotones();  
            }
        }
    }//GEN-LAST:event_btnPuntoEnContraActionPerformed

    private void btnContinuanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuanteActionPerformed
        cod_punto = 3;
        AreaSeleccionada();
        MovimientoSeleccionado();
        jugador = JugadorSeleccionado();
        if (jugador == 0) {
            JOptionPane.showMessageDialog(null, "Verifique que tiene un jugador seleccionado", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            if (cod_movimiento == 0 || cod_area == 0) {
                JOptionPane.showMessageDialog(null, "Verifique que tenga un area y/o movimiento seleccionado", " ERROR", JOptionPane.ERROR_MESSAGE);
            }else{
                Recopilacion();
                ReinicioBotones();  
            }
        }
        

    }//GEN-LAST:event_btnContinuanteActionPerformed

    private void btnDefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDefensaActionPerformed

    private void btnTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitularActionPerformed
        if (titulares < 6) {
            modeloJugadores = metodos.cambioDeTabla(jtJugadores, jtTitulares2, modeloJugadores, modeloTitulares2);
            jtJugadores.setModel(modeloJugadores);
            titulares ++;
        } else{
            JOptionPane.showMessageDialog(null, "Tiene mas titulares de lo permitido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTitularActionPerformed

    private void btnCambio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambio1ActionPerformed
        if (cambios < 6) {
            modeloJugadores = metodos.cambioDeTabla(jtJugadores, jtCambios2, modeloJugadores, modeloCambios2);
            jtJugadores.setModel(modeloJugadores);
            cambios ++;
        }else{
            JOptionPane.showMessageDialog(null, "Tiene mas cambios de lo permitido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCambio1ActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
        cod_titulares = metodos.codigoJugadores(jtTitulares2);
        cod_cambios = metodos.codigoJugadores(jtCambios2);
        
        NuevoSet.dispose();
        
        MostrarJugadores(cod_titulares, jtTitulares);
        MostrarJugadores(cod_cambios, jtCambios);
        
        if (bandera == true) {
            saca = false;
            bandera = false;
        } else if (bandera == false) {
            saca = true;
            bandera = true;
        }
        Saque();
        jl1.setText(Integer.toString(cod_titulares[0]));
        jl2.setText(Integer.toString(cod_titulares[5]));
        jl3.setText(Integer.toString(cod_titulares[4]));
        jl4.setText(Integer.toString(cod_titulares[3]));
        jl5.setText(Integer.toString(cod_titulares[2]));
        jl6.setText(Integer.toString(cod_titulares[1]));
    }//GEN-LAST:event_btnSiguienteActionPerformed

    // <editor-fold defaultstate="collapsed" desc="Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame NuevoSet;
    private javax.swing.JToggleButton btnA1;
    private javax.swing.JToggleButton btnA2;
    private javax.swing.JToggleButton btnA3;
    private javax.swing.JToggleButton btnA4;
    private javax.swing.JToggleButton btnA5;
    private javax.swing.JToggleButton btnA6;
    private javax.swing.JButton btnBack;
    private javax.swing.JToggleButton btnBloqueo;
    private javax.swing.JButton btnCambio;
    private javax.swing.JButton btnCambio1;
    private javax.swing.JToggleButton btnColoque;
    private javax.swing.JButton btnContinuante;
    private javax.swing.JToggleButton btnDefensa;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnPuntoEnContra;
    private javax.swing.JToggleButton btnRecibo;
    private javax.swing.JToggleButton btnRegresar_Titulares;
    private javax.swing.JToggleButton btnRemate;
    private javax.swing.JToggleButton btnSaque;
    private javax.swing.JToggleButton btnSiguiente;
    private javax.swing.JButton btnTitular;
    private javax.swing.JToggleButton btn_Regresar_Cambio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl2;
    private javax.swing.JLabel jl3;
    private javax.swing.JLabel jl4;
    private javax.swing.JLabel jl5;
    private javax.swing.JLabel jl6;
    private javax.swing.JLabel jlEquipoA;
    private javax.swing.JLabel jlEquipoB;
    private javax.swing.JLabel jlPuntosA;
    private javax.swing.JLabel jlPuntosB;
    private javax.swing.JLabel jlSet;
    private javax.swing.JLabel jlSetsGanadosA;
    private javax.swing.JLabel jlSetsGanadosB;
    private javax.swing.JTable jtCambios;
    private javax.swing.JTable jtCambios2;
    private javax.swing.JTable jtJugadores;
    private javax.swing.JTable jtTitulares;
    private javax.swing.JTable jtTitulares2;
    private javax.swing.JPanel pnlAreas;
    private javax.swing.JPanel pnlJugadas;
    private javax.swing.JPanel pnlRotuloPartido;
    private javax.swing.JPanel pnlTablaPartido;
    // End of variables declaration//GEN-END:variables
    // </editor-fold>
    
    protected void MostrarJugadores(int [] cod_jugadores, javax.swing.JTable tabla){
   
      String[] titulos = {"Codigo", "Nombre", "Apellido", "Numero", "Posicion", "Codigo Equipo"};
      DefaultTableModel modelo = new DefaultTableModel(null, titulos);
      
      String[] registros = new String[6];
      
      String SQL = "Select * from jugadores";
      
      try{
          
          Statement st = con.createStatement();
          ResultSet rs = st.executeQuery(SQL);
          
          while(rs.next()){
              for (int i = 0; i < cod_jugadores.length; i++) {
                   if(rs.getInt("cod_jugador") == cod_jugadores[i]){
                    registros[0] = rs.getString("cod_jugador");
                    registros[1] = rs.getString("Nombre");
                    registros[2] = rs.getString("Apellidos");
                    registros[3] = rs.getString("Numero_Jugador");
                    registros[4] = rs.getString("Posicion");
                    if(registros[4].equals("1")){
                        registros[4] = "Pasador";
                    } else if(registros[4].equals("2")){
                        registros[4] = "Lateral";
                    }else if(registros[4].equals("3")){
                        registros[4] = "Quinto";
                    } else if(registros[4].equals("4")){
                        registros[4] = "Centro";
                    }else{
                        registros[4] = "Libero";
                    }
                    registros[5] = rs.getString("cod_equipo_de_jugador");  

                    modelo.addRow(registros);
                  }else{

                  }
              }
             
          }
          
          tabla.setModel(modelo);
          
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, "ERROR AL MOSTRAR JUGADORES" + e.getMessage());
      }   
   }
    
    protected void Cambio(){
        int filaSeleccionadaTitular = jtTitulares.getSelectedRow();
        int filaSeleccionadaCambio = jtCambios.getSelectedRow();
        
        String titular [] = new String[6];
        String cambio [] = new String[6];
        
        
        
        if (filaSeleccionadaTitular >= 0 && filaSeleccionadaCambio >= 0) {            
            for (int i = 0; i < 6; i++) {
                titular[i] = jtTitulares.getValueAt(filaSeleccionadaTitular, i).toString();
                cambio[i] = jtCambios.getValueAt(filaSeleccionadaCambio, i).toString();
            }
            
            int codTitular = Integer.parseInt(titular[0]);
            int codCambio = Integer.parseInt(cambio[0]);
            
            for (int i = 0; i < cod_titulares.length; i++) {
                
                if (cod_titulares[i] == codTitular) {
                    cod_titulares[i] = codCambio;
                }
                
            }
            for (int i = 0; i < cod_cambios.length; i++) {
                if (cod_cambios[i] == codCambio) {
                    cod_cambios[i] = codTitular;
                }
            }
            
            for (int i = 0; i < 6; i++) {
               jtTitulares.setValueAt(cambio[i], filaSeleccionadaTitular, i);
               jtCambios.setValueAt(titular[i], filaSeleccionadaCambio, i);
            }
        }
    }

    private void AreaSeleccionada(){
        
        if (btnA1.isSelected()) {
            cod_area = 1;
        } else if (btnA2.isSelected()) {
            cod_area = 2;
        }else if (btnA3.isSelected()) {
            cod_area = 3;
        }else if (btnA4.isSelected()) {
            cod_area = 4;
        }else if (btnA5.isSelected()) {
            cod_area = 5;
        } else if (btnA6.isSelected()) {
            cod_area = 6;
        } 
    }
    
    private void MovimientoSeleccionado(){
        if (btnSaque.isSelected()) {
            cod_movimiento = 1;
        } else if (btnRemate.isSelected()) {
            cod_movimiento = 2;
        }else if (btnBloqueo.isSelected()) {
            cod_movimiento = 3;
        }else if (btnRecibo.isSelected()) {
            cod_movimiento = 4;
        }else if (btnColoque.isSelected()) {
            cod_movimiento = 5;
        } else if (btnDefensa.isSelected()) {
            cod_movimiento = 7;
        }
    }
    
    private void Saque(){
        
        if(saca == true){
            jLabel1.setText("Saca: " + Integer.toString(cod_titulares[0]));
        }else if(saca == false){
            jLabel1.setText("No saca");
        }
        
    }

    private void NuevoSet(){
        if (puntosA >= 25 || puntosB >= 25) {
           if (puntosA >= puntosB + 2) {
                setsA ++;
                jlSetsGanadosA.setText("Sets Ganados: " + Integer.toString(setsA));
                puntosA = 0;
                puntosB = 0;
                jlPuntosB.setText("Puntos: " + Integer.toString(puntosB));
                jlPuntosA.setText("Puntos: " + Integer.toString(puntosA));
                set ++;
                jlSet.setText("Set: " + Integer.toString(set));
                CrearSet();
                NuevoSet.show(true);
                NuevoSet.setSize(997, 883);
                NuevoSet.setLocationRelativeTo(null);
            
            } else if (puntosB >= puntosA + 2) {
                setsB ++;
                jlSetsGanadosB.setText("Sets Ganados: " + Integer.toString(setsB));
                puntosA = 0;
                puntosB = 0;
                jlPuntosB.setText("Puntos: " + Integer.toString(puntosB));
                jlPuntosA.setText("Puntos: " + Integer.toString(puntosA));
                set ++;
                jlSet.setText("Set: " + Integer.toString(set));
                CrearSet();
                NuevoSet.setVisible(true);
                NuevoSet.setSize(997, 883);
                NuevoSet.setLocationRelativeTo(null);
            }
            Ganados();
            if (setsA != 3 || setsB != 3) {
                NuevoSetSetUP();
            } 
        }
        
    }
    
    private void CrearSet(){
       
        try{
            
            String SQL = "insert into sets (cod_partido) value (?)";
            
            PreparedStatement pst = con.prepareStatement(SQL);
            pst.setInt(1, cod_partido);
            
            pst.execute();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al crear set " + e.getMessage());
        }
    }
    
    private void Ganados(){
        if (setsA == 3) {
            int input = JOptionPane.showOptionDialog(null, "El equipo " + equipoA + " gana con " + setsA + " vs " + equipoB + " con " + setsB + ". ", "Resultados", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
            
            if(input == JOptionPane.OK_OPTION){
                NuevoSet.dispose();
                
                Menu menu = new Menu();

                Main.Escritorio.add(menu);
                menu.setVisible(true);
                menu.setSize(Main.Escritorio.getSize());

                this.dispose();
            }
            
        }else if (setsB == 3) {
            int input = JOptionPane.showOptionDialog(null, "El equipo " + equipoB + " gana con " + setsB + " vs " + equipoA + " con " + setsA + ". ", "Resultados", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

            if(input == JOptionPane.OK_OPTION){
                NuevoSet.dispose();
                Menu menu = new Menu();

                Main.Escritorio.add(menu);
                menu.setVisible(true);
                menu.setSize(Main.Escritorio.getSize());

                this.dispose();
            }
            
        }
    }
    
    private Integer JugadorSeleccionado(){
        int cod_jugador = 0;
        try{
            if (saca == true && cod_movimiento == 1) {
                cod_jugador = cod_titulares[0];
            } else{
                cod_jugador = Integer.parseInt(jtTitulares.getValueAt(jtTitulares.getSelectedRow(), 0).toString());
                return cod_jugador;
            }
        }catch(Exception e){
            
        }
        return cod_jugador;
    }
    
    private void Recopilacion(){
        
        String SQL = "insert into datos (cod_jugador, cod_equipo, cod_set, cod_movimiento, cod_area, cod_punto) values (?, ?, ?, ?, ?, ?)";
        int cod_set = metodos.codSet();
        
        try{

           PreparedStatement pst = con.prepareStatement(SQL);
           
           pst.setInt(1, jugador);
           pst.setInt(2, cod_equipo);
           pst.setInt(3, cod_set);
           pst.setInt(4, cod_movimiento);
           pst.setInt(5, cod_area);
           pst.setInt(6, cod_punto);
           
           
           pst.execute();
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al ingresar datos " + e.getMessage());
        }
       
    }
    
    private void ReinicioBotones(){
        
        btnA1.setSelected(false);
        btnA2.setSelected(false);
        btnA3.setSelected(false);
        btnA4.setSelected(false);
        btnA5.setSelected(false);
        btnA6.setSelected(false);
        btnSaque.setSelected(false);
        btnRemate.setSelected(false);
        btnBloqueo.setSelected(false);
        btnRecibo.setSelected(false);
        btnColoque.setSelected(false); 
        btnDefensa.setSelected(false);
        cod_movimiento = 0;
        cod_area = 0;
        MostrarJugadores(cod_titulares, jtTitulares);
    }
    
    private void NuevoSetSetUP(){
        
        titulares = 0;
        cambios = 0;
        
        modeloTitulares2.setRowCount(0);
        modeloCambios2.setRowCount(0);
        
        
        int [] cod_jugadores = new int [12];
        
        for (int i = 0; i < cod_titulares.length; i++) {
            cod_jugadores[i] = cod_titulares[i];
        }
        
        
        
        for (int i = 0; i < cod_cambios.length ; i++) {
            cod_jugadores[i + 6] = cod_cambios[i];
            
        }
        
        for (int i = 0; i < cod_titulares.length; i++) {
            cod_titulares[i] = 0;
            cod_cambios[i] = 0;
        }
        
        MostrarJugadores(cod_jugadores, jtJugadores);
        MostrarJugadores(cod_titulares, jtTitulares2);
        MostrarJugadores(cod_cambios, jtCambios2);
        
    }
   
}
