/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;

import java.awt.Component;
import conexion.conexionSQL;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class NuevoJugador extends javax.swing.JInternalFrame {

    conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();
    
    
    public NuevoJugador() {
        initComponents();
        Rectangle screenSize = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration().getBounds();
        int width = (int)screenSize.getWidth();
        int height = (int)screenSize.getHeight();
        
        this.setSize(width, height);
        jlTitulo.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnCrearPerfilJugador.setAlignmentX(Component.CENTER_ALIGNMENT);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNumeroDJugador = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        jlApellidos = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlPosicion = new javax.swing.JLabel();
        jlNumeroDJuagdor = new javax.swing.JLabel();
        btnCrearPerfilJugador = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cmbPosicion = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jlTitulo.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 0, 0));
        jlTitulo.setText("Nuevo Jugador");

        txtNumeroDJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDJugadorActionPerformed(evt);
            }
        });

        jlApellidos.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlApellidos.setForeground(new java.awt.Color(255, 0, 0));
        jlApellidos.setText("Apellidos");

        jlNombre.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlNombre.setForeground(new java.awt.Color(255, 0, 0));
        jlNombre.setText("Nombre");

        jlPosicion.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlPosicion.setForeground(new java.awt.Color(255, 0, 0));
        jlPosicion.setText("Posicion");

        jlNumeroDJuagdor.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlNumeroDJuagdor.setForeground(new java.awt.Color(255, 0, 0));
        jlNumeroDJuagdor.setText("Numero de Jugador");

        btnCrearPerfilJugador.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCrearPerfilJugador.setText("Crear Perfil de Jugador");
        btnCrearPerfilJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPerfilJugadorActionPerformed(evt);
            }
        });

        btnBack.setText("Regresar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cmbPosicion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbPosicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Posicion", "Pasador", "Lateral", "Quinto", "Centro", "Libero" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlTitulo)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombre)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jlNumeroDJuagdor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(194, 194, 194))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jlNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(304, 304, 304)))
                            .addComponent(txtNumeroDJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(291, 291, 291))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlPosicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(300, 300, 300))
                                    .addComponent(txtApellidos)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(cmbPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(btnCrearPerfilJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(437, 437, 437))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jlNumeroDJuagdor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlPosicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroDJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(364, 364, 364)
                .addComponent(btnCrearPerfilJugador)
                .addGap(149, 149, 149))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearPerfilJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPerfilJugadorActionPerformed
        insertarDatos();
       
        int reply = JOptionPane.showConfirmDialog(null, "Quiere seguir agregando jugadores? ", "Mensaje", JOptionPane.YES_NO_OPTION );
        
        if(reply == JOptionPane.NO_OPTION){
            Menu menu = new Menu();

            Main.Escritorio.add(menu);
            menu.setVisible(true);
            menu.setSize(Main.Escritorio.getSize());

            this.dispose();
        } else{
           limpiarCajas();
        }
    }//GEN-LAST:event_btnCrearPerfilJugadorActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Menu menu = new Menu();
        
        Main.Escritorio.add(menu);
        menu.setVisible(true);
        menu.setSize(Main.Escritorio.getSize());
        
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtNumeroDJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDJugadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCrearPerfilJugador;
    private javax.swing.JComboBox<String> cmbPosicion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlApellidos;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNumeroDJuagdor;
    private javax.swing.JLabel jlPosicion;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroDJugador;
    // End of variables declaration//GEN-END:variables

public void insertarDatos(){
    
    try{
        String SQL = "insert into jugadores (Nombre, Apellidos, Numero_Jugador, Posicion, cod_equipo_de_jugador) value (?, ?, ?, ?, ?)";
        
        PreparedStatement pst = con.prepareStatement(SQL);
        pst.setString(1, txtNombre.getText());
        pst.setString(2, txtApellidos.getText());
        int numeroDeJugador = Integer.parseInt(txtNumeroDJugador.getText());
        pst.setInt(3,numeroDeJugador);
        int posicionJugador = cmbPosicion.getSelectedIndex();
        pst.setInt(4, posicionJugador);
        pst.setInt(5, 81);
        
        
        pst.execute();
        
        
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "ERROR DE REGISTRO" + e.getMessage());
    }
    
}

public void limpiarCajas(){
    
    txtNombre.setText("");
    txtApellidos.setText("");
    txtNumeroDJugador.setText("");
    
}

}
