/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;

import conexion.conexionSQL;
import java.awt.Component;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author jsaca
 */
public class SeleccionarEditarEquipos extends javax.swing.JInternalFrame {

    
   conexionSQL cc = new conexionSQL();
   Connection con = cc.conexion();
   
   Metodos metodos = new Metodos();
   
   int cod_equipo_seleccionado;
    public SeleccionarEditarEquipos() {
        initComponents();
        Rectangle screenSize = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration().getBounds();
        int width = (int)screenSize.getWidth();
        int height = (int)screenSize.getHeight();
        
        this.setSize(width, height);
        btnSiguiente.setAlignmentX(Component.CENTER_ALIGNMENT);
        jlInstrucciones.setAlignmentX(Component.CENTER_ALIGNMENT);
        jtEquipos.setAlignmentX(Component.CENTER_ALIGNMENT);
        metodos.mostrarEquipos(jtEquipos);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jlInstrucciones = new javax.swing.JLabel();
        btnBack3 = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtEquipos = new javax.swing.JTable();

        jPanel4.setBackground(new java.awt.Color(0, 0, 153));

        jlInstrucciones.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jlInstrucciones.setForeground(new java.awt.Color(255, 0, 0));
        jlInstrucciones.setText("Seleccione el equipo a editar");

        btnBack3.setText("Regresar");
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jtEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtEquiposMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtEquipos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(537, 537, 537)
                        .addComponent(jlInstrucciones))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(601, 601, 601)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(512, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack3)
                .addGap(164, 164, 164)
                .addComponent(jlInstrucciones)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        Equipos equipos = new Equipos();

        Main.Escritorio.add(equipos);
        equipos.setVisible(true);
        equipos.setSize(Main.Escritorio.getSize());

        this.dispose();
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

        cod_equipo_seleccionado = metodos.codEquipoSeleccionado(jtEquipos);
        EditarEquipos eq = new EditarEquipos(cod_equipo_seleccionado);
              
        Main.Escritorio.add(eq);
        eq.setVisible(true);
        eq.setSize(Main.Escritorio.getSize());
        
        this.dispose();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void jtEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtEquiposMouseClicked

    }//GEN-LAST:event_jtEquiposMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlInstrucciones;
    private javax.swing.JTable jtEquipos;
    // End of variables declaration//GEN-END:variables

    
    
}
